---
output:
   bookdown::pdf_book:
    toc: false
    keep_tex: true
    fig_caption: yes
title: "Dissertation RP"
subtitle: "In partial preparation of submission ..."
author: 
    | 
    | Rocco Paolillo 
    | Bremen International Graduate School of Social Sciences
    | University of Bremen & Jacobs University Bremen
    | Mary-Somerville-Str. 9, 28359 Bremen, Germany  
    | rpaolillo@bigsss-bremen.de
    | 
    | **` SOME SHORT NOTES: `**
    | **` OK `**
    |  
date: "Any note `r format(Sys.time(), '%d/%m/%y %H %M')`"
language: en-GB
bibliography: "references.bib"
csl: apa.csl
# always_allow_html: yes

# target: BIGSSS Research Day by September 15th, presented  on October 25th. 6000 words: around 12 pages.
# csl: apa.csl # by default: Chicago style
header-includes:
- \usepackage{float}
- \usepackage{multirow}
- \usepackage{xcolor} 
- \usepackage{amsmath}
- \usepackage{graphicx}
---

\newcommand{\rocco}[1]{{\textcolor{red}{Rocco: #1}}} <!-- % to add comments -->
\newcommand{\jan}[1]{{\textcolor{blue}{jan: #1}}} <!-- % to add comments -->
\newcommand{\andreas}[1]{{\textcolor{green}{andreas: #1}}} <!-- % to add comments -->
\newcommand{\michael}[1]{{\textcolor{yellow}{michael: #1}}} <!-- % to add comments -->
\newcommand{\adalbert}[1]{{\textcolor{purple}{adalbert: #1}}} <!-- % to add comments -->



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)



```

\newpage

\begin{centering}

{\bf Executive Summary}

\end{centering}

WHAT: The topic and focus  

Society is made up of people belonging to different groups. 
Residential segregation is a crucial issue to social policies, interested in reducing spatial segregation and foster integration.
From a theoretical point of view, much researc has been interested in developing quantitative measures of spatial segregation, qualitative research on the residential preferences of people and how these translate into spatial segregation. 
A critical interest in the social sciences is to understand the mechanisms and dynamics of how individual residential preferences can translate into spatial segregation. This dissertation is rooted in this area of research. 
Agent-based modelling and analytical sociology, social complexity are widely recognized as a valid tool to understand such phenomena.   

PREVIOUS RESEARCH

Thomas Schelling proposed in the last 60's a noteworthy agent-based modelling to show how individual preferences could translate into spatial segregation.
In particular, the model builds on threshold preferences, i.e. the minimal fraction of similar ones in neighborhood composition to remain in a neighborhood. 
The main contribution of the model is to show how spatial segregation can result from even low preferences for similar ones through cascades effect of individual relocations. 
The model has a wide application in describing residential ethnic segregation.     

BUT     

However, societies today shows some features that clash with the original assumptions of Schelling's model and its application in ethnic segregation literature in Western societies.
First, society is inertly diverse, the paradigm majority-minority does not work anymore as much as minority-minority.
A growing stream of literature shows how other forms of spatial segregation have emerged, e.g. socio-economic status, cultural similarity, education, etc.
Other forms of categories can drive homophily preferences in the residential decisions. This is first a theoretical opportunity that can be applied to Schelling's model, as well as seems an empirical evidence of modern, diverse societies. 

WHAT IS NEW?      

This dissertation focuses on this aspect: membership of individuals and definition of similarity based on other cross-ethnic categories, heterogeneity of homophily preferences and tolerance towards diversity among people who belong to the same group for one dimension (primarly ethnicity) but differ for secondary characteristics or attitude.

HOW AND WHAT 

\rocco{first paper, definition of tolerance: threshold = 0 we are indifference}
In a first paper, we extend the original Schelling threshold model focusing on diverse definition of similarity between agents.
We focus on the interaction of conservative agents who define similarity based on shared ethnicity, indifferent to other characteristics, and tolerant value-oriented agents who define similarity based on shared value for tolerance towards ethnic diversity.
Results show how the introduction of value oriented agents diminishes ethnic segregation compared to the original Schelling model, though a new form of value segregation emerges. We identify critical points were all agents can be satisfied with neighborhoods.

\rocco{second paper, definition of tolerance: weight of dominant >= secondary preference}
In a second paper, we translate the model into a discrete choice random utility model.
This not only updates to more recent research in Schelling's literature, but also serves different aims.
First, discrete choice random utility models allow to model decision making in residential segregation, modeling the weight for each preference, which translates into randomness of behavior and test robustness of emerging phenomena. 
Additionally, we tested a mix of preferences with both ethnic and value preference for each type of agent and imposing a dominant and a secondary preference, along with different population structure in terms of ethnic and value sizes. 
We specifically focus on how segregation scenarios would differ if a minority population would become more or less liberal.
Results show how a tendency towards segregation remains a main outcome of relocation decision, through ethnic integration can be reached as an intermediate state due to a combination of higher randomness and relative group sizes. 
The most robust result is value segregation of conservatives, as in the ACS paper: that it is robust since appears both in threshold model and linear function.

\rocco{third paper, definition of tolerance: taste for diversity/push towards integration}
A third and final paper tested specifically utility functions where agents are not simply tolerant to diversity but aim at living in specifically integrated neighborhoods for the two dimensions. Compared to the second paper, this paper delves into different shapes of utility functions between threshold and linear preferences in addition to weight attributed to each of the utility dimensions in the relocation choice.
Intermediate preferences between integrationist and segregationist extreme are tested, to test how robust results in the previous two papers could be when different shapes of utility function are implemented.

CONTRIBUTIONS AND LIMITS    

The aim of this contribution is to extend the understanding of dynamics of urban segregation in front of a more complex society compared to the one described in the original Schelling model.
Limits of the dissertation are discussed in the perspective of future research line and relation with empirical data.

\newpage

\tableofcontents

\newpage

\listoffigures
\newpage
\listoftables
\newpage

# Introduction

## Residential segregation
\rocco{the aim here should be ultimately to justify the focus on micro-macro dynamics, i.e. social complexity as a paradigm and agent-based modelling as a tool -> the same research question is on the dynamics of segregation}
* What is it, why important
* Lines of research: 
    * quantitative measurements (Duncan: eveness,dissimilarity etc.)
    * qualitative: individual relocation decisions and life course
    * reasons and processes:
        * Spatial Assimilation Theory (focus on minority, gaining economic power move to more affluent (historically white) neighborhoods)
        * Place stratification Theory (local stakeholders (e.g. real estates): planned exclusion of minority)
        * But the main question remains: how the dynamics work? See @van2012neighborhood \rocco{this justifies more abm as a method than Schelling's contribution themselves. I would rather add a paragraph on need of analytical sociology/social complexity as need, and abm as a tool}
        * An alternative model: Schelling's model
        
## Schelling model

\rocco{ I think a connection is feasible and I think worthy. I'm not saying Schelling's did his work because of the new legislation, I don't remember something similar, but he mentions segregation by color as main concern '69 paper.}

### Historical/academic background: years of end of racial laws and planned segregation (late 60's). Schelling was an economist and wanted to demonstrate how some forms of segregation could be "unplanned", emerging from the interaction of individual preferences. {-}

### Original aim: explain unplanned segregation as aggregating outcome of individual preferences in limited spatial constraints.{-} 

### Description of the model and main contribution {-}

The basic condition of Schelling model is that similarity of agents is defined as a "twofold, exhaustive and recognizable distinction" [@schelling69, p.488].
What I describe here is known as the spatial proximity, or checkerboard version of the model.
Consider two groups of agents who reside on a lattice grid (a checkerboard) that represents a city, so that each individual agent occupies a cell of the grid and considers the set of the eight surrounding agents as its own ‘neighborhood’. 
Some spots are empty on the checkerboard.
Agents are divided by color^[This is a description of the model adapted from @leon2017analytical, \rocco{for the red/blue scenario, delete in the end if any}].
At each time-step, one agent can choose whether to stay or to leave. 
Its residential moves depend on the concentration of similar agents in the neighborhood, quantified by a threshold.
If the concentration of desired similar agents in the local neighborhood falls below the desired threshold, the agent leave to a random sport.
The contribution of the model is to describe how the interaction of individuals subscribing to a similar behavior can translate into high levels of segregation \rocco{and high levels even with mild preferences, check if add here or later}
Imagine one red agent starts. 
If the percentage of other red agents in the neighborhood falls below the threshold, the agent relocates to one of the empty spots on the checkerboard, so to leave its previous spot in the old neighborhood empty. 
By doing so, the red agent changes the composition of both its previous neighborhood and its new one.
In particular, the percentage of same-color agents decreases for other red agents left in the previous neighborhood, while it increases for other red agents in the new neighborhood. 
In this way, the previous neighborhood becomes less attractive for the remained red agents, who could leave when it is their turn to decide. On the contrary, the new neighborhood becomes more attractive both to other red agents who already live there (who are then more prone to stay) and potentially to unsatisfied red agents living in other neighborhoods. The same works for blue agents.
Through the change in neighborhoods’ compositions, therefore, the relocation decision of each agent has unwillingly a cascade effect on the next agent to decide. 
This enables a self-reinforcing dynamic so that some neighborhoods become progressively less attractive for agents of one group and more attractive for those of the other group. In other words, the concentration of one group in the neighborhood reinforces its attractiveness for other in-group members when they decide to relocate. 
This, in turn, can lead to high segregation—even with relatively tolerant agents.

* The impact of the model in literature: considered one of the first agent-based modelling, though not in the intention of Schelling. Influence in the agent-based literature. Known also in empirical studies of spatial segregation
* Focus on agent-based modelling literature: BRIEFLY: extensions, application to other methods, e.g. GIS. In details in each section of the papers
* What remains as a stable result: tendency towards segregation as a stable outcome

## BUT 
\rocco{here it must be a paragraph driving the reader to what is the research question/justification of the dissertation, then in details with the literature}
* More recent literature on spatial segregation in Western societies shows some results that contrast Schelling's assumptions and scenarios
* Results: ethnic segregation is decreased, while other forms of segregation have emerged (e.g. socio-economic status)
* Societies are inherently different. The paradigm majority-minority most literature on ethnic segregation was built on (see School of Chicago and spatial assimilation) not stand. Different paradigms emerge (see @crul2016super, @vertovec2007super)

\rocco{here it becomes tricky: diverse type of segregation as the aspect that clashes with Schelling's framework}
## New forms of Residential segregation
* As an outcome: residential segregation experienced on diverse forms at at different levels for members of the same ethnic group or social class or other categories
* New residential preferences alternative to ethnic homophily:
    + Increased preference for diversity for some members of the same social category
    + Diverse ethnic tolerance
    + Preference for other forms of similarity


## Superdiverse societies
* Society is more diverse compared to the historical context Schelling built on and to the theoretical assumption of similarity based on ethnicity as an exclusive dimension:
* Sociodemographic changes:
    * the paradigm majority-minority (e.g. white vs black) does not work anymore, rather an amalgama of ethnicities (see @vertovec2007super) as effect of new generations of migrants' descendents and faster international mobility
    * correlation ethnicity/social class: members of minority can be in upper class, members of majority being in the lower class
\rocco{though majority still holds a numeric majority and in the upper class, it is changing}
* In such a complex scenario, the process of defining boundaries of membership become relevant: Ethnic boundary making

## Ethnic Boundary Making
* dynamic process of definition of inclusion
* ethnicity not an exclusive category


# Aim of dissertation
* Given these observations on modern diverse societies and different complex scenarios of spatial segregation, how can we bring Schelling to these scenarios? In particular the question evolves into:
- What are the consequences of different definition of similarity?
- What different types of spatial segregation would emerge? And what other, if any, unexepcted consequences?
- How can spatial segregation being reduced out of these extensions?
- Main scenario investigated: definition of similarity based on ethnic membership vs cross-ethnic supposedly inclusive category (in the model description value)
- Different degree of preference or tolerance for either similarity based on the own group membership
\rocco{the next point is crucial and should be well developed, summarizing what specific niche/scenario the dissertation proposes as advance to Schelling's framework and research question(s), and then move with specific literature}
* Out of such diversity, other categories people belong to can matter in the definition of similarity and neighborhood preferences, independent on and complementary to ethnic membership. People belonging to different groups can hold different degree of preferences for ethnic membership or alternative categories.
* This is both a theoretical possibility and an empirical evidence as growing empirical literature shows
* It can contribute to lower ethnic segregation and show more complex scenarios of segregation


\newpage
# Paper 1
* Aim: exploration of what are the consequences of different definition of similarity; effect of relative group size
* Extension: different definition of similarity, remaining into a deterministic, deterministic model and threshold function
* Literature associated? More focused on ethnic boundary making and homophily preferences
* Model description: tolerant agents value-oriented vs intolerant ethnicity-oriented
* Measures: exposure, density
* Experiments: parameter sweeping
* Results: decrease ethnic segregation due to tolerant agents, spillover effect

\newpage
# Paper 2
* Aim: Understand better mechanisms associated with different homophily preferences and heterogeneity for value/ethnic similarity, how integration for both or either dimensions can be reached?
* Explore consequences of a mix of preferences for ethnic and value similarity in both types of agents, mantaining dominant and secondary preference; effect of ethnic ratio and value distribution in minority
* Extension: probabilistic model and linear utility function random utility model: to represent the decisional process, a weight for each dimension and robustness of emerging results (randomness); ethnic ratio and value distribution of minority
* \rocco{here it risks to be tricky: a theoretical section, or mention briefly?} Here literature on discrete choice random utility: utility models (empirical science McFadden...), utility function vs probability function, what differs between abm and regression models. Literature in abm: Bruch-Van Rijt discussions...

Random utility models for discrete choice have a long history in housing research [@frankhauser2016deciding] and in recent years they have been applied in the agent-based modeling framework [@bruch2006neighborhood,bruch2012methodological].
Stemming from the utility maximization paradigm, these model assume that the decisional process underlying the choice of economic actors is unknown, and it can be deduced by observed preferences, i.e. how selection of respondents differ for attributes of the options available [@hess2018revisiting], e.g. different neighborhood composition. So, aim of regression models comparing choices of the sample is to estimate vector parameters that quantify the likelihood to select one option over the other depending on the  difference in their attributes [@manski1977structure]. 
Utility in this context is defined as the attractiveness for each characteristic the options differ for and it is based on the response curve of the respondent [@bruch2015agent,train2009discrete] imposed based on the theoretical model of the analyst.
Nevertheless, random utility models divide between a systematic component of utility, i.e. observable differences between options based on their utility, and a random term, representing all unknown factors associated with selection of that options, might they depend on other characteristics of the option, characteristics of the selector or an interaction of both. Compared to our model, random utility for a generic neighborhood is:


\begin{equation}
    U = \beta_e U_e + \beta_v U_v + \epsilon
\end{equation}

where: \par
$\beta_e$ = weight parameter for ethnic similarity, with $\beta_e [0, \infty)$ \par
$U_e$ = ethnic utility of neighborhood \par
$\beta_v$ = weight parameter for value similarity, with $\beta_v [0, \infty)$  \par
$U_v$ = value utility of neighborhood  \par
$\epsilon$ = random term \par

While parameters $\beta_e$ and $\beta_v$ can be estimated  through regression models, the random term $\epsilon$ remains unknown. The conditional logit model introduced by  [@mcfadden1973conditional] is a specific type of discrete choice model that allow to quantify the effect of systematic utility over random component, though remaining the latter unknown. Assuming the random term $\epsilon$ follows a type I extreme value distribution, e.g. Gumbel distribution, the probability to select neighborhood \textit{j} out of options \textit{k} in choice set \textit{C} is:


\begin{equation}
P_{j\in{C}} = \frac{exp(\beta_e U^e_j + \beta_v U^v_j)}{\sum\limits_{{k\in{C}}}exp(\beta_e U^e_k + \beta_v U^v_k)}
\label{eq:cndtnl}
\end{equation}

<!-- from AF paper, cut out -->

In this computation of probability, parameters $\beta_e$ and $\beta_v$ become the weight of how much the systematic component of utility for that dimension matters in the selection of the option compared to the random component represented  by the unknown random term. The higher $\beta_e$ or $\beta_v$, the higher the likelihood that the option with highest utility for that dimension will be selected, the lower $\beta_e$ or $\beta_v$, the higher the chance that an option is selected randomly for that dimension. With both $\beta_e$ and $\beta_v$ equal 0, the all options have equal probability to be selected, since the choice is totally stochastic, i.e. dependent on random term.


Implementation of discrete choice in agent-based modelling has a  number of peculiarities compared to empirical regression models. First and above all, estimated preferences in regression models depend on a the comparison of a limited set of observed cases that can profoundly affect results. 
Moreover, utility remains a random variable estimated through parameters $\beta$ and computation of probability to select one option.
Probability to select one option over the others as behavioral response to change in their attributes is the equivalent to utility. 
As [@bruch2009preferences] stress out, agent-based modeling are deeply different in this aspect, allowing to model independently and quantify the elements of the conditional logit based on a theoretical model. 
Researchers can impose different combinations of utility function for all ranges of neighborhood characteristics and parameters $\beta$ in the relocation decisions of agents to observe their aggregated results. Additionally, modellers can include other elements that contribute to the dynamics of emerging spatial segregation, such as diverse heterogeneous distributions of preferences (see [@xie2012modeling]) or population structures that can influence neighborhood composition [@bruch2014population].

Also agent-based modelling can benefit from the implementation of discrete choice models, not only for the formalization of the decisional process of agents and calibration with parameters $\beta$ estimated [@bruch2006neighborhood], but also for the inclusion of the stochastic random term. Randomness is useful to both test robustness of observed phenomena in complex systems and increase their realism through inclusion of random fluctuations against deterministic behavior.
A traditional way to include randomness in the dynamics of an agent-based model is as an external noise, for  instance in Schelling model, with a percentage of agents, or additional agents, forced to randomly relocate by the researcher. 
Implementation of discrete choice allows to include randomness as an endogenous component in the relocation decision of individual agents through the random term compared to parameters of determinism. 
Useful to our interest in the interplay of value and ethnic preferences, the parameter $\beta$ can vary as a local variable of agents, so to sort out differences in the ratio between deterministic and random relocation depending on characteristics of agents. 
We build on this peculiarity of random utility models to test how random behavior of a specific type of agents for value orientation, ethnicity or a combination of both can influence the emergence of stable equilibria of hybrid segregation. 
We can moreover explore the interdependence between different types of agents and how determinism of agents would react to different distributions of the two characteristics of ethnicity and value orientation in the population. In the next section we describe our extension of [@paolillo2018] and how we implemented random utility discrete choice.





* Model description
* Measures: exposure, spatial clutering for asymmetric conditions
* Experiments: parameter sweeping, more sensitivity analysis
* Results: by-product value segregation of conservatives (ex spillover effect) better understood, as effect of more robust/denser neighborhoods of liberals, integration can be reached as an intermediate state towards segregation, due to a mix of lower randomnes, ethnic and value size. Effect of ethnic ratio on effect of weights: By-product of majority size over minority, specific scenario of liberals minority.

\newpage
# Paper 3?
* Aim: definition of tolerance as integrationist preferences: push towards integration. Would this reduce by-product value segregation that appeared both in threshold and discrete choice version, and reduce ethnic segregation?
* Model description
* Experiments
* Results

\newpage
# Conclusions
* What can we say about segregation dynamics?
- Effect of cross-ethnic preferences vs ethnic preferences: what is the difference, through neighborhood density
- Effect of relative weights (discrete choice implementation)
- Effect of relative group and value size
- Intermediate levels of integration as effect of randomness, preference and relative size
- What unexpected results were reached? How strong segregation emerges even if integrationist attitudes?

\newpage
# Discussion
* Difference between deterministic threshold model vs discrete choice model: what changes? Theta 0 = beta 0, high determinism small fluctuations due to randomness
* How a threshold and a discrete  choice model differ? How robut results are across different implementations?
* Comparison with discrete choice models in empirical science used e.g. to estimate parameters determinism $\beta$ and utility function: 
- observed preference (e.g. from census data): equilibria are already emerged and other factors (or dynamics) context-specific could cause segregation
- stated preference (e.g. survey): other factors could intervene, so that the actual segregation could be not derived from individual stated preference
- In the end, they reply to a different question: The aim in regression models is to estimate and validate individual preferences from data. The aim of abm is to observe aggregated results and formalize their dynamics, plus the possibility to model separately utility function and probability function (see @bruch2009preferences) and impose any range of parameters \rocco{connects with limits/future agenda: what is the use of theoretical models vs data-driven models for spatial sciences}

\newpage
# Limits and Future Research Agenda
* Limits
- Focus/contribution for modelling/complexity literature over empirical literature in residential studies
- Theoretical models vs data-driven models
- However, contribution of abm is to understand mechanisms, which justifies theory-driven models.
* Data
* Validation in the future, we know the dynamics and unexpected consequences of individual preferences based on diverse definition of similarity, and sociodemographic conditions
* comparsion with empirical data: what type of data? During the Phd different surveys and aggregate neighborhood data were explored which could have fit the model -> need to have joint probability -> micro data
* Additional layers: other socio-demographic characteristics, and resources associated



\newpage
# Appendix





# References
